//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int id { get; set; }
        public int Login_id { get; set; }
        public string RoleName { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
